---
title: "**Development and Displacement**: "
---
# An Examination of the Effects of New Development on Residential Mobility in Boston from 2005 to 2019

## By Brian Froeb
## May 2020

<br> 
**Abstract**

As housing prices increase in American cities the number of low-income households choosing or being forced to move has also increased. One explanation for this trend are the impacts of new housing and commercial development. Using a unique data set gathered from tax returns the impacts of new development on household mobility were assessed using logistic regression though a GIS framework. Additional variables were included from a variety of data sets to account for individual and neighbor factors related to household mobility including age, race, relationship status, and eviction rate. It was found that new commercial development was associated with an increased likelihood of moving and new residential development was insignificant. These findings do not support the hypothesis that increased residential development is responsible for the increase in housing mobility. Additionally, these findings support the theory that access to amenities, not supply and demand, is the dominant factor in determining housing prices.

<br>

*Keywords: GIS, Housing Mobility, Residential Development, Housing, Displacement, Forced and Unforced Mobility, Poverty, and Gentrification.*
