---
title: "Chapter 1:"
subtitle: "Introduction"
output: html_document
---

Many Americans living in cities are experiencing the worst housing crisis since the 1950s. Housing costs have been rising consistently since the 1990s as incomes in the US have remained flat (Anenberg & Kung, 2018; Desmond, 2018; HUD, 2018; Sugrue, 2014). This has created an affordability crisis, where low and middle income Americans, both homeowners and renters, face the choice of either remaining in their current housing and becoming housing cost burdened or seeking increasingly rare affordable housing elsewhere (Desmond, 2018; HUD, 2018). Housing burdened is defined as dedicating more than 30% of household income to housing costs and is becoming increasingly common in the US but especially for low-income households (Anenberg & Kung, 2018; Desmond, 2018). 

Housing mobility, how often an individual or household moves to new housing, has also increased as housing costs have risen. Housing mobility is especially common among American families that rent their home, which is currently at a fifty year high of 37% (Anenberg & Kung, 2018) . The goal of this thesis is to examine the factors that are associated with to household mobility among low-income residents of Boston between 2005 and 2019.
  
In a study of the fifty most populous combined statistical areas (CBSA), which represented around 210 million Americans in 2018, only nine experienced a decrease in their housing cost burdened population. Among the most rent burdened CBSAs were Los Angeles, San Diego, Miami, New York, San Francisco, and Boston (Anenberg & Kung, 2018). San Francisco, and other major California cities, have drawn a sizable portion of housing research in the United States. This is partially due to the number of housing cost burdened households in these cities, 48% of households in San Francisco and 62% in Los Angeles, but also to the pronounced effects of gentrification and displacement (Anenberg & Kung, 2018; Pennington, 2018). San Francisco, and the Bay Area in general have experienced significant decreases in minority populations since the 1990s. This is likely because minority workers tend to earn less than their white counterparts and cannot afford the increased rent (Desmond & Gershenson, 2017; Pendall et al., 2006). The African American population of San Francisco shrank by 45% between 1990 and 2015 and the Latinx population of the Mission district was 60% in 2000 and is projected to shrink to around 31% without any form of intervention (Pennington, 2018). 

While Boston is experiencing an increase in its minority population, with Suffolk County becoming a minority majority county in 2017, housing prices have soared (Modestino et al., 2019). House and condo prices in the bottom twenty percent have doubled from an average of $200,000 to $400,000 and rents have risen to some of the highest in the country, only exceeded by San Francisco and Los Angeles. Additionally, rents in Boston are rising significantly faster than other major cities, including New York and San Francisco (Modestino et al., 2019). Production of new housing units in Boston is also well behind where it needs to be to keep up with demand. From 2015 to 2017 50,000 new units needed to be constructed to keep up with population growth, but only 35,000 permits were issued (Modestino et al., 2019). Many of these developments have been luxury housing targeting high income households. These new developments are justified by planning and zoning boards for increasing overall supply: higher income residents move into these new units freeing up their old units. However, this process does not appear to be working as envisioned, and often new units just raise the average rent in the neighborhood (HUD, 2018; Zuk & Chapple, 2016).

These conditions make Boston an appropriate study location for household mobility among low-income Americans. The data on development from the Boston Planning and Development Agency (BPDA) and longitudinal data from the Boston Tax Help Coalition (BTHC), allow for unique insights into the effects of new development on household mobility. Specifically, these data present an opportunity to examine if there is a connection between new development and household mobility, as well as spatial data patterns within this connection. 
