---
title: "Chapter 2: Literature Review"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
      
---

There are many factors that affect a household’s propensity to move, either directly or indirectly, and many of these are not under direct control of the household. These can broadly be divided into individual factors, such as age and income, and neighborhood characteristics, such as crime and eviction rates. 

# Individual Factors

A variety of individual factors have been studied in relation to household mobility, including income, number of children, dissolution of romantic relationships, race, gender, disability status, educational attainment, and age. These factors have been shown to have significant effects on household mobility in previous research (Desmond, 2016; Desmond & Gershenson, 2017). 

Income has long been associated with residential mobility, generally the impact of income and economic status has been found to be curvilinear (Desmond et al., 2015). According to this model both residents with lower economic status and higher economic status tend to have higher mobility than those with middle economic status and can be represented as a curvilinear relationship. It is theorized that residents with lower economic status were more likely to experience forced mobility, or displacement, though evictions (both formal and informal), rising rents, and other measures out of their control (Desmond & Gershenson, 2017; Phinney, 2013). Meanwhile, higher economic status allows residents to move more frequently to chase trends and live in “up and coming neighborhood.” Middle income residents move significantly less often than low or high income residents (Desmond et al., 2015). There is evidence that suggests that middle income residents cannot afford to chase trends like high income residents or have less than market rate housing costs which makes moving undesirable (Coulton et al., 2012; Mateyka, 2015). However, research into middle income household stability has been inconclusive. Results from studies on middle income residential mobility have varied significantly more between cities than studies of high or low income (Coulton et al., 2012; Mateyka, 2015).  Because the BTHC data comes from low income populations, a negative linear relationship is expected between income and residential mobility.

Using income as a variable allows for the examination of another important factor, namely employment status (Desmond et al., 2015; Mulder & Malmberg, 2011). Changes in employment have often been associated with household mobility. Households move to housing that is either more affordable in the case of job loss, or more expensive and presumably more desirable housing when finding a better job or receiving a promotion (Desmond et al., 2015; Mulder & Malmberg, 2011; Pendall et al., 2006). While the BTHC does not directly collect information on employment, changes to income can effectively reflect mobility based on household income.

Multiple studies have shown that when other factors are taken into account families with children were significantly more likely to be evicted than families without children (Desmond et al., 2013; Desmond & Gershenson, 2017). A study of children and eviction in Milwaukee found that families with no children had a 7.3 percent chance of being evicted in a given year, this increased to 9.5 percent with one child, and 11.7 percent with two children (Desmond & Gershenson, 2017). Multiple studies have found that women are more likely to be evicted than men (Desmond, 2012; Lempert & Monsma, 1994). It is possible that this is due to women retaining custody of children in a divorce (Desmond, 2012; Desmond & Gershenson, 2017). Another possible explication is that women were more likely to be targeted by subprime lenders (Baker, 2014).

Studies on race have shown mixed results on displacement, some showing an effect and some showing little to no effect, often depending on how displacement was assessed (Coulton et al., 2012; Desmond & Gershenson, 2017). On measures using eviction, little to no effect was observed between eviction and race. Some studies have found that racial discrimination related to housing access likely does not play a factor in the legal mechanism of displacement (Desmond, 2012; Desmond & Gershenson, 2017; Lempert & Monsma, 1994). In effect, landlords willing to accept tenants of color in the first place are not considering race when evicting their tenants (Desmond & Gershenson, 2017). However, studies that take a more holistic look at displacement have found that black and latinx households are disproportionately displaced.  These studies have used a variety of measures, including tracking household addresses, formal and informal evictions, and illegal practices such as utility shut offs and lock outs (Massey et al., 2010; Rugh, 2015).

Not all moves are related to displacement, in fact many moves are a part of everyday life. The average American will move 11.7 times over the course of their life according to the US census (Chalabi, 2015). These moves can be cause by the dissolution of a relationship, partners moving in together, moving for school or work, or the need for different housing due to life events (Coulton et al., 2012; Mulder & Malmberg, 2011). These events could include the birth of a new child, children leaving the home, or new housing to accommodate a disability (Fischer & Malmberg, 2001). 

Generally speaking, the likelihood of moving decreases as individuals get older, outside their 20s where moves become more common (Fischer & Malmberg, 2001; Mulder & Malmberg, 2011). Highly educated individuals are more likely than less educated individuals to move, either to gain access to more specialized labor markets or as a course of their education, moving to attend school or study abroad. Additionally, those with higher educations are also more likely to have higher incomes and more likely to have unforced mobility (Desmond et al., 2015; Mulder & Malmberg, 2011).

# Neighborhood Factors

Neighborhood factors, including eviction rates, crime rates, average rent, and the effects of new development are often found to be more significant in mobility research focusing on displacement (Coulton et al., 2012; Desmond & Gershenson, 2017; Freeman, 2005). 

In a 2017 study on eviction, Desmond and Gershenson found that the number of evictions in a neighborhood were positively correlated with the likelihood of a resident experiencing eviction. They believed that this is because landlords tend to operate in informal cabals. Landlords often tend to spatially cluster their properties and therefore interact with other landlords in their neighborhoods (Fligstein, 1996; Logan & Molotch, 2007). Through these interactions business practices tend to diffuse spatially, resulting in neighborhoods where eviction is more common than other neighborhoods (Dobbin et al., 2007). 

Crime rate was studied in the context of eviction by Desmond and Gerhenson but has also been studied in the context of mobility in general, by Coulton et al. in 2012. Both studies found similar results, the safer residents felt in their neighborhood the less likely they were to move or let themselves be evicted. 

Gentrification has long been the focus of housing research, often with mixed results. Some studies have shown that landlords in gentrifying areas are more likely to evict their clients or raise their rents to force them out (Marcuse, 1986; Newman & Wyly, 2006). Other studies have found either no relationship between gentrification and mobility (Vigdor et al., 2002). Gentrification has also been found to lead to decreased mobility among low-income renters as renters in these neighborhoods make “greater efforts to remain in their dwelling units, even if the proportion of their income devoted to rent rises” (Freeman & Braconi, 2004, p. 51).

While gentrification is a buzzword in the popular press and academic discourse, it is difficult to define quantitatively (K. Williams, 2015). Many of the quantitative approaches have varied including property value, the number of new coffee shops in an area, and indices created using a variety of metrics (K. Williams, 2015). However, studies using these quantitative approaches often have results that are solely dependent on the gentrification measure used. When the study is replicated using a different quantitative approach the results often contradict each other. If these measures were accurate in quantifying gentrification the approach used should have minimal effect on the outcome of the study (K. Williams, 2015). Therefore, many of the commonly used measurements of gentrification may not be accurate in reflecting displacement or do not fully capture causality (K. Williams, 2015). For this reason, this paper will not use any measure of gentrification and instead focus on more measurable contextual factors, such as new development.

# The Effects of New Development

One of the causes or effects of gentrification, depending on the theoretical framework adopted by the study, is new commercial development (Pennington, 2018). These developments include both housing and other amenities and often appear in neighborhoods that could gentrify or are in the process of gentrifying. The exact impact of these developments on both rent and displacement has become a point of contention between housing policy advocates, urban planners, economists, and renters (Pennington, 2018). 

According to some experts, new housing developments may have some effect on gentrifying neighborhoods, but they will generally decrease the cost of housing in the area even if they are built at market rate (Anenberg & Kung, 2018; Boulay, 2012). This theory is based on the assumption that increasing the housing supply will cause older units to filter through the housing supply (Pennington, 2018). Filtering is the process of affluent renters moving from less expensive housing to more expensive housing, which increases the supply of less expensive housing stock. This theoretically should drive prices down and lower the risk of displacement in the neighborhood (Zuk & Chapple, 2016). These experts argue that increases in rental prices and housing value are likely caused by over restrictive land use regulations which artificially limit the housing supply (Kok et al., 2014; Pennington, 2018).

Other experts note that new housing developments have spillover effects and cause nearby units to appreciate in value, which increases displacement pressures in a neighborhood (Pennington, 2018). Previous research shows that buildings within roughly a quarter mile of a new development tend to appreciate in value (Hornbeck & Keniston, 2017). Other research showed that renovated units result in significant demographic changes not just in renovated units but also units within 200 feet of the renovated unit (Redding & Sturm, 2016). Some studies also argue that affluent renters do not filter up to more expensive housing. Research by the Institute of Governmental Studies at the University of California, found that in the United States rental units become occupied by a lower income household at a rate of 2.2 percent per year, this rate is even smaller in strong housing markets like California or New England. Rents, however, only drop by a rate of 0.3 percent per year meaning it would take roughly 15 years for median income housing to become affordable to 80 percent median income and 50 years for 50 percent median income (Zuk & Chapple, 2016).

It is possible that both these effects, spillover and filtering, are occurring at the same time but vary spatially. One theoretical explanation is that new housing development increases rent and displacement pressure where it is built, but lowers rent and pressures on units further away (Pennington, 2018). Research also suggests that subsidized housing development significantly lowers displacement pressure on a regional scale (Zuk & Chapple, 2016).

Neighborhood factors are especially important for planners and policy makers. Significant neighborhood factors indicate that location is related to household mobility and place-based policies, like anti-eviction zones and zoning ordinances, are easier to implement and enforce than policies addressing individual characteristics (Desmond & Gershenson, 2017; HUD, 2018; Pennington, 2018).

# Limitations of Previous Research

One of the limitations of much of the previous research surrounding household mobility is the difficulty in acquiring accurate data (Pennington, 2018). Most studies focus on legal, or formal, evictions because the court documents are public record and relatively easy to get a hold of. However, eviction is only one of the many mechanisms responsible for displacement. Other mechanisms that can be used by a landlord include informal, i.e. non-legal, evictions, rent hikes, threats, utility shutoffs, lock outs, or any other pressure put on the tenet by their landlord encouraging them to move against their will. Additional mechanisms include a landlord experiencing foreclosure or a house being condemned (Desmond et al., 2015).

Perhaps the most complete data set collected on household mobility is the Milwaukee Area Renters Survey (MARS) collected by a research team led by Matthew Desmond. The MARS instrument included 250 questions and was completed by 1,086 renters in Milwaukee between 2009 and 2011. It collected previous addresses, reasons for moving, and demographic data (Desmond, 2016).  One of the limitations of this study is its generalizability. Firstly, it covers a limited geographic context so the generalizability of its results to other US cities is questionable, especially cities like San Francisco and Boston which have significantly different housing markets. Secondly, it has a limited temporal window and covers the years directly following the great recession and the foreclosure crisis of 2007 (Desmond et al., 2015). 

Additionally, much of the previous work on displacement has focused on census tracts or other areal units that aggregate data (Bousquet, 2017; Corriston et al., 2017; Easton et al., 2019; Freeman, 2005). This introduces the modifiable areal unit problem (MAUP) (Openshaw, 1984; Wong, 2009). The MAUP is a source of error when using data aggregated to an arbitrary spatial unit, such as census tracts or zip code tabulation areas (ZCTA), which represent a postal service area (Openshaw, 1984; US Census, 2019). A common example of the MAUP is observed gerrymandering, where politicians redraw districts to improve their odds of reelection. These divisions can be drawn in an almost infinite number of ways (Fotheringham & Rogerson, 2009; Wong, 2009). Different aggregations can also benefit research as well, as aggregation protects individual privacy. This tradeoff between privacy and accuracy is usually considered acceptable. However, it always creates the uncertain geographic context problem (UGCoP) (Park & Kwan, 2018). In the next chapter I discuss the data used in this thesis.
